# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    container_name: master
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - myNetwork

  mongo:
    container_name: wm-mongo
    image: mongo:4.4.7-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge